// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710192247_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityName_EntityId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_UserId_CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_blogs");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Blogs_CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Blogs_Slug");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("IX_Blogs_Status_PublishedAt");

                    b.ToTable("Blogs", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_blog_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogCategories_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogCategories_Slug");

                    b.ToTable("BlogCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C#, ASP.NET Core, API và kiến trúc backend.",
                            IsActive = true,
                            Name = "Backend",
                            Slug = "backend"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ReactJS, TypeScript và UI/UX.",
                            IsActive = true,
                            Name = "Frontend",
                            Slug = "frontend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kinh nghiệm học tập và phát triển nghề nghiệp.",
                            IsActive = true,
                            Name = "Career",
                            Slug = "career"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_blog_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogTags_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_BlogTags_Slug");

                    b.ToTable("BlogTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASP.NET Core",
                            Slug = "aspnet-core"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Entity Framework Core",
                            Slug = "entity-framework-core"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ReactJS",
                            Slug = "reactjs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JWT",
                            Slug = "jwt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SQL Server",
                            Slug = "sql-server"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogTagMapping", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("integer")
                        .HasColumnName("blog_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("BlogId", "TagId")
                        .HasName("pk_blog_tag_mappings");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_BlogTagMappings_TagId");

                    b.ToTable("BlogTagMappings", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CredentialId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("credential_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.HasKey("Id")
                        .HasName("pk_certificates");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Certificates_IsActive");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_contact_messages");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_ContactMessages_Status_CreatedAt");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("degree");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<string>("GPA")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gpa");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("major");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("school_name");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_education");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Education_IsActive");

                    b.ToTable("Education", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "College",
                            Description = "Tập trung vào lập trình web, cơ sở dữ liệu, phân tích và thiết kế hệ thống.",
                            EndYear = 2026,
                            GPA = "7.3/10",
                            IsActive = true,
                            Major = "Information Technology",
                            SchoolName = "Ho Chi Minh City Industry and Trade College",
                            StartYear = 2023
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("company_logo_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Technologies")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("technologies");

                    b.HasKey("Id")
                        .HasName("pk_experiences");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Experiences_IsActive_DisplayOrder");

                    b.ToTable("Experiences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Personal Projects",
                            Description = "Phân tích nghiệp vụ, thiết kế cơ sở dữ liệu, xây dựng RESTful API và phát triển giao diện web responsive.",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsCurrent = true,
                            Location = "TP. Hồ Chí Minh",
                            Position = "Full-Stack Developer",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "C#, ASP.NET Core, EF Core, SQL Server, ReactJS, TypeScript"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Inter K",
                            Description = "Tìm hiểu và triển khai quy trình DMS, theo dõi đơn hàng, nhập kho, trả hàng và báo cáo phục vụ nghiệp vụ.",
                            DisplayOrder = 2,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsCurrent = false,
                            Location = "TP. Hồ Chí Minh",
                            Position = "IT Intern",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "DMS, SQL, Business Analysis, Technical Support"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .HasColumnType("text")
                        .HasColumnName("about_me");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("banner_url");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cv_url");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("facebook_url");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_bio");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Profiles_IsActive");

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "Tôi tập trung xây dựng Web API, thiết kế cơ sở dữ liệu và giao diện web hiện đại. Tôi có kinh nghiệm thực hành với ASP.NET Core, Entity Framework Core, SQL Server, ReactJS và TypeScript.",
                            Address = "TP. Hồ Chí Minh, Việt Nam",
                            Email = "nthanhvu1411@gmail.com",
                            FullName = "Nguyễn Thanh Vũ",
                            GithubUrl = "https://github.com/nguyenthanhvu1411",
                            IsActive = true,
                            JobTitle = "Fresher Full-Stack Developer",
                            Phone = "+84374797826",
                            ShortBio = "Full-Stack Developer định hướng C#, ASP.NET Core và ReactJS."
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DemoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("demo_url");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text")
                        .HasColumnName("full_description");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_name");

                    b.Property<string>("ProjectType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_type");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Projects_Slug");

                    b.HasIndex("IsActive", "IsFeatured", "Status")
                        .HasDatabaseName("IX_Projects_PublicDisplay");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullDescription = "WMS xây dựng bằng ASP.NET Core, Entity Framework Core, SQL Server, ReactJS và TypeScript; hỗ trợ FIFO/FEFO, lot/serial, JWT, RBAC và audit log.",
                            IsActive = true,
                            IsFeatured = true,
                            ProjectName = "Enterprise Warehouse Management System",
                            ProjectType = "Full-stack Web Application",
                            Role = "Full-Stack Developer",
                            ShortDescription = "Hệ thống quản lý kho với các luồng nhập, xuất, tồn kho, điều chuyển, kiểm kê và trả hàng.",
                            Slug = "enterprise-warehouse-management-system",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullDescription = "Hệ thống gồm các nghiệp vụ giỏ hàng, đơn hàng, thanh toán, voucher và hoàn tiền; sử dụng JWT, API Gateway, Eureka và VNPay.",
                            IsActive = true,
                            IsFeatured = true,
                            ProjectName = "E-Commerce Microservices",
                            ProjectType = "Microservices Web Application",
                            Role = "Backend / Full-Stack Developer",
                            ShortDescription = "Nền tảng thương mại điện tử theo kiến trúc microservices.",
                            Slug = "ecommerce-microservices",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            FullDescription = "Portfolio sử dụng ASP.NET Core Web API, SQL Server, ReactJS và TypeScript; hỗ trợ quản lý hồ sơ, kỹ năng, dự án, blog, tin nhắn liên hệ và thống kê lượt xem.",
                            IsActive = true,
                            IsFeatured = true,
                            ProjectName = "Developer Portfolio",
                            ProjectType = "Full-stack Web Application",
                            Role = "Full-Stack Developer",
                            ShortDescription = "Website Portfolio có trang public và hệ thống quản trị nội dung.",
                            Slug = "developer-portfolio",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_thumbnail");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_images");

                    b.HasIndex("ProjectId", "DisplayOrder")
                        .HasDatabaseName("IX_ProjectImages_ProjectId_DisplayOrder");

                    b.ToTable("ProjectImages", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("ProjectId", "SkillId")
                        .HasName("pk_project_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("IX_ProjectSkills_SkillId");

                    b.ToTable("ProjectSkills", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 7
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 14
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 15
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 6
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 7
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 11
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 13
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 15
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 2
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 6
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 7
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 14
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 15
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_Token");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Toàn quyền quản trị hệ thống Portfolio.",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quản lý nội dung Portfolio.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("favicon_url");

                    b.Property<string>("FooterText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("footer_text");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("seo_title");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.Property<string>("ThemeColor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("theme_color");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "nthanhvu1411@gmail.com",
                            FooterText = "© 2026 Nguyễn Thanh Vũ. All rights reserved.",
                            SeoDescription = "Portfolio cá nhân giới thiệu kỹ năng, dự án và kinh nghiệm phát triển phần mềm.",
                            SeoTitle = "Nguyễn Thanh Vũ - Full-Stack Developer",
                            SiteName = "Nguyễn Thanh Vũ Portfolio",
                            ThemeColor = "#2563EB"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<string>("Level")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Skills_CategoryId");

                    b.HasIndex("IsActive", "IsFeatured", "DisplayOrder")
                        .HasDatabaseName("IX_Skills_PublicDisplay");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "RESTful API"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DisplayOrder = 5,
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Name = "Java Spring Boot"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "ReactJS"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Name = "Tailwind CSS"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Intermediate",
                            Name = "Clean Architecture"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Advanced",
                            Name = "JWT & RBAC"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_SkillCategories_Name");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_SkillCategories_IsActive_DisplayOrder");

                    b.ToTable("SkillCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ngôn ngữ và framework phía máy chủ.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Công nghệ xây dựng giao diện web.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hệ quản trị và thiết kế cơ sở dữ liệu.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Công cụ phát triển, quản lý mã nguồn và triển khai.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Tools & DevOps"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kiến trúc phần mềm, xác thực và phân quyền.",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Architecture & Security"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.HasIndex("StoredFileName")
                        .HasDatabaseName("IX_UploadedFiles_StoredFileName");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("IX_UploadedFiles_UploadedBy");

                    b.ToTable("UploadedFiles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ViewStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlogId")
                        .HasColumnType("integer")
                        .HasColumnName("blog_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("page_path");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<DateTime>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_view_statistics");

                    b.HasIndex("BlogId", "ViewedAt")
                        .HasDatabaseName("IX_ViewStatistics_BlogId_ViewedAt");

                    b.HasIndex("PagePath", "ViewedAt")
                        .HasDatabaseName("IX_ViewStatistics_PagePath_ViewedAt");

                    b.HasIndex("ProjectId", "ViewedAt")
                        .HasDatabaseName("IX_ViewStatistics_ProjectId_ViewedAt");

                    b.ToTable("ViewStatistics", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Blog", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.BlogCategory", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Blogs_BlogCategories_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogTagMapping", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Blog", "Blog")
                        .WithMany("BlogTagMappings")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlogTagMappings_Blogs_BlogId");

                    b.HasOne("Portfolio.Domain.Entities.BlogTag", "Tag")
                        .WithMany("BlogTagMappings")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlogTagMappings_BlogTags_TagId");

                    b.Navigation("Blog");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectImages_Projects_ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectSkill", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectSkills_Projects_ProjectId");

                    b.HasOne("Portfolio.Domain.Entities.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectSkills_Skills_SkillId");

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.SkillCategory", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Skills_SkillCategories_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.User", "User")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UploadedFiles_Users_UploadedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles_RoleId");

                    b.HasOne("Portfolio.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users_UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ViewStatistic", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Blog", "Blog")
                        .WithMany("ViewStatistics")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ViewStatistics_Blogs_BlogId");

                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany("ViewStatistics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ViewStatistics_Projects_ProjectId");

                    b.Navigation("Blog");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Blog", b =>
                {
                    b.Navigation("BlogTagMappings");

                    b.Navigation("ViewStatistics");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlogTag", b =>
                {
                    b.Navigation("BlogTagMappings");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectImages");

                    b.Navigation("ProjectSkills");

                    b.Navigation("ViewStatistics");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
